import assert from'node:assert/strict';
import{createState,placeBuilding,buildError,count,validateSave}from'../dist/rules.js';
import{makeGenome}from'../dist/genetics.js';
import{normalizeExpansion,tickExpansion,toggleRide,commandPet}from'../dist/expansion.js';
import{normalizeTravel,moveTravel}from'../dist/navigation.js';
import{normalizeHousing}from'../dist/housing.js';
import{ISLANDS}from'../dist/islands.js';
import{normalizeShip,claimIsland,startFusion,tickShip,fusionChecks,boardShip,takeHelm,leaveHelm,climbShip,disembark,transferCargo,toggleLounge,fireCannon,deckWalk,shipDockOption,restPlace,LIMITS,FUSION_COST,SHIP_POINTS,DECKS}from'../dist/ship.js';
import{monologue}from'../dist/guide.js';
import{makeWarship}from'../dist/ship-models.js';
import{MeshStandardMaterial}from'../dist/vendor/three.module.min.js';
const test=(name,fn)=>{fn();console.log('PASS '+name);};
const rich=s=>{for(const k of Object.keys(s.resources))s.resources[k]=2000;return s;};
function base(){const s=rich(normalizeTravel(createState(42)));s.secret=true;normalizeExpansion(s);s.tamed=[{id:'p1',name:'夥伴',genome:makeGenome(7,0),generation:0,bond:40,stamina:100,health:100,penId:null}];return s;}
function maxed(){const s=base();for(let x=0;x<4;x++)for(let z=0;z<5;z++)if(!s.buildings.some(b=>b.type==='floor'&&b.x===x&&b.z===z))assert.ok(placeBuilding(s,'floor',x,z).ok,`floor ${x},${z}`);for(let z=0;z<5;z++)assert.ok(placeBuilding(s,'pen',-1,z).ok);normalizeHousing(s);normalizeExpansion(s);return s;}
function claimPalm(s){const i=ISLANDS.find(v=>v.id==='palm');Object.assign(s.player,{mode:'foot',x:i.x,z:i.z,level:0});s.expedition.activeId='p1';return claimIsland(s,'palm',s.tamed[0]);}
test('Shelter caps foundations at 20 and pens at 5',()=>{const s=maxed();assert.equal(count(s,'floor'),LIMITS.floor);assert.equal(count(s,'pen'),LIMITS.pen);assert.match(buildError(s,'floor',4,0),/上限/);assert.match(buildError(s,'pen',-1,5)||buildError(s,'pen',4,4),/上限/);});
test('Island claim needs landing, a bonded guardian and materials; dock needs a claim',()=>{const s=maxed();assert.match(buildError(s,'dock',4,2),/占領/);s.tamed[0].bond=20;assert.equal(claimPalm(s).ok,false);s.tamed[0].bond=40;const wood=s.resources.wood;assert.ok(claimPalm(s).ok);assert.equal(s.resources.wood,wood-20);assert.equal(claimPalm(s).ok,false);assert.equal(restPlace(s,s.tamed[0]),'island');Object.assign(s.player,{mode:'foot',x:3,z:3});assert.equal(buildError(s,'dock',4,2),null);assert.ok(placeBuilding(s,'dock',4,2).ok);assert.match(buildError(s,'dock',4,3),/上限/);});
test('Fusion is gated by every requirement, costs materials, takes time, and yields a docked warship',()=>{const s=maxed();claimPalm(s);Object.assign(s.player,{mode:'foot',x:3.6,z:3.6,level:0});placeBuilding(s,'dock',4,2);placeBuilding(s,'shelter',1,1);assert.equal(startFusion(s).ok,false);assert.ok(fusionChecks(s).some(([n,ok])=>!ok&&n.includes('LV')));s.expedition.boatLevel=3;const metal=s.resources.metal;assert.ok(startFusion(s).ok,JSON.stringify(fusionChecks(s)));assert.equal(s.resources.metal,metal-FUSION_COST.metal);assert.equal(startFusion(s).ok,false);s.elapsed+=60;tickShip(s);assert.equal(s.ship,undefined);s.elapsed+=61;tickShip(s);assert.ok(s.ship);assert.ok(validateSave(JSON.parse(JSON.stringify(s))));const loaded=normalizeShip(JSON.parse(JSON.stringify(s)));assert.ok(loaded.ship.cargo);});
function shipState(){const s=maxed();claimPalm(s);Object.assign(s.player,{mode:'foot',x:3.6,z:3.6,level:0});placeBuilding(s,'dock',4,2);placeBuilding(s,'shelter',1,1);s.expedition.boatLevel=3;startFusion(s);s.elapsed+=200;tickShip(s);return s;}
test('Boarding lands on the main deck and only the bridge helm can steer',()=>{const s=shipState();Object.assign(s.player,{x:s.ship.x,z:s.ship.z});assert.equal(shipDockOption(s).mode,'board-ship');assert.ok(boardShip(s).ok);assert.equal(s.player.mode,'aboard');assert.equal(s.player.deck,3);assert.equal(takeHelm(s).ok,false);const st=SHIP_POINTS.find(p=>p.id==='to-bridge');Object.assign(s.player,{lx:st.lx,lz:st.lz});assert.ok(climbShip(s,'to-bridge').ok);assert.equal(s.player.deck,4);const h=SHIP_POINTS.find(p=>p.id==='helm');Object.assign(s.player,{lx:h.lx,lz:h.lz});assert.ok(takeHelm(s).ok);assert.equal(s.player.mode,'ship');const x=s.ship.x,z=s.ship.z;s.player.heading=s.ship.heading;moveTravel(s,Math.sin(s.ship.heading)*-3,Math.cos(s.ship.heading)*-3);moveTravel(s,0,-6);assert.ok(Math.hypot(s.ship.x-x,s.ship.z-z)>.5,'ship moved');assert.ok(leaveHelm(s).ok);assert.equal(s.player.deck,4);});
test('Five decks connect by ladders; cargo holds and lounge enforce their rules',()=>{const s=shipState();Object.assign(s.player,{x:s.ship.x,z:s.ship.z});boardShip(s);const go=id=>{const p=SHIP_POINTS.find(v=>v.id===id);Object.assign(s.player,{lx:p.lx,lz:p.lz});return climbShip(s,id);};assert.ok(go('down-3').ok);assert.equal(DECKS[s.player.deck].id,'lounge');assert.ok(go('down-2').ok);assert.ok(go('down-1').ok);assert.equal(s.player.deck,0);assert.equal(transferCargo(s,'food',10).ok,false);const wood=s.resources.wood;assert.ok(transferCargo(s,'wood',50).ok);assert.equal(s.ship.cargo.wood,50);assert.equal(s.resources.wood,wood-50);assert.ok(transferCargo(s,'wood',-20).ok);assert.equal(s.ship.cargo.wood,30);assert.equal(go('down-1').ok,false);for(const d of[0,1,2,3])assert.ok(deckWalk(d,0,0));assert.equal(deckWalk(0,6,0),false);assert.ok(toggleLounge(s,'p1').ok);assert.equal(restPlace(s,s.tamed[0]),'lounge');s.ship.x+=500;assert.equal(toggleLounge(s,'p1').ok,false);});
test('Disembark requires the gangway near a shore; cannon needs the helm and ammo',()=>{const s=shipState();Object.assign(s.player,{x:s.ship.x,z:s.ship.z});boardShip(s);const g=SHIP_POINTS.find(p=>p.id==='gangway');Object.assign(s.player,{lx:g.lx,lz:g.lz});assert.ok(disembark(s).ok);assert.equal(s.player.mode,'foot');boardShip(s);Object.assign(s.player,{mode:'ship'});s.wild.push({id:'h',x:s.ship.x+10,z:s.ship.z,hostile:true,genome:makeGenome(1,0),hp:30});s.resources.metal=0;assert.equal(fireCannon(s).ok,false);s.resources.metal=5;assert.ok(fireCannon(s).ok);assert.equal(s.resources.metal,4);assert.equal(fireCannon(s).ok,false);});
test('Monologue guide always names a next step and advances with progress',()=>{const s=normalizeTravel(createState(3));assert.equal(monologue(s).id,'salvage');s.salvaged=3;assert.equal(monologue(s).id,'floor');const t=shipState();assert.equal(monologue(t).id,'helm');});
test('Warship model builds five cut-away deck bands',()=>{const g=makeWarship((c,e={})=>new MeshStandardMaterial({color:c,...e}),()=>{});assert.equal(g.userData.bands.length,5);assert.ok(g.userData.bands.every(b=>b.children.length>5));});
